package com.thanlinardos.resource_server.batch.keycloak.event;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonValue;

public enum KeycloakUserEventType {

    REGISTER("REGISTER", true),
    REGISTER_ERROR("REGISTER_ERROR", false),
    RESTART_AUTHENTICATION_ERROR("RESTART_AUTHENTICATION_ERROR", false),
    CUSTOM_REQUIRED_ACTION_ERROR("CUSTOM_REQUIRED_ACTION_ERROR", false),
    CLIENT_LOGIN("CLIENT_LOGIN", false),
    UPDATE_TOTP("UPDATE_TOTP", true),
    SEND_VERIFY_EMAIL("SEND_VERIFY_EMAIL", true),
    VERIFY_EMAIL("VERIFY_EMAIL", false),
    LOGIN("LOGIN", false),
    LOGIN_ERROR("LOGIN_ERROR", false),
    LOGOUT("LOGOUT", false),
    LOGOUT_ERROR("LOGOUT_ERROR", false),
    CODE_TO_TOKEN("CODE_TO_TOKEN", false),
    UPDATE_PASSWORD("UPDATE_PASSWORD", false),
    RESTART_AUTHENTICATION("RESTART_AUTHENTICATION", false),
    AUTHREQID_TO_TOKEN("AUTHREQID_TO_TOKEN", false),
    AUTHREQID_TO_TOKEN_ERROR("AUTHREQID_TO_TOKEN_ERROR", false),
    CLIENT_DELETE("CLIENT_DELETE", false),
    CLIENT_DELETE_ERROR("CLIENT_DELETE_ERROR", false),
    CLIENT_INFO("CLIENT_INFO", false),
    CLIENT_INFO_ERROR("CLIENT_INFO_ERROR", false),
    CLIENT_INITIATED_ACCOUNT_LINKING("CLIENT_INITIATED_ACCOUNT_LINKING", false),
    CLIENT_INITIATED_ACCOUNT_LINKING_ERROR("CLIENT_INITIATED_ACCOUNT_LINKING_ERROR", false),
    CLIENT_LOGIN_ERROR("CLIENT_LOGIN_ERROR", false),
    CLIENT_REGISTER("CLIENT_REGISTER", false),
    CLIENT_REGISTER_ERROR("CLIENT_REGISTER_ERROR", false),
    CLIENT_UPDATE("CLIENT_UPDATE", false),
    CLIENT_UPDATE_ERROR("CLIENT_UPDATE_ERROR", false),
    CODE_TO_TOKEN_ERROR("CODE_TO_TOKEN_ERROR", false),
    CUSTOM_REQUIRED_ACTION("CUSTOM_REQUIRED_ACTION", false),
    DELETE_ACCOUNT("DELETE_ACCOUNT", false),
    DELETE_ACCOUNT_ERROR("DELETE_ACCOUNT_ERROR", false),
    EXECUTE_ACTION_TOKEN("EXECUTE_ACTION_TOKEN", false),
    EXECUTE_ACTION_TOKEN_ERROR("EXECUTE_ACTION_TOKEN_ERROR", false),
    EXECUTE_ACTIONS("EXECUTE_ACTIONS", false),
    EXECUTE_ACTIONS_ERROR("EXECUTE_ACTIONS_ERROR", false),
    FEDERATED_IDENTITY_LINK("FEDERATED_IDENTITY_LINK", false),
    FEDERATED_IDENTITY_LINK_ERROR("FEDERATED_IDENTITY_LINK_ERROR", false),
    GRANT_CONSENT("GRANT_CONSENT", false),
    GRANT_CONSENT_ERROR("GRANT_CONSENT_ERROR", false),
    IDENTITY_PROVIDER_FIRST_LOGIN("IDENTITY_PROVIDER_FIRST_LOGIN", false),
    IDENTITY_PROVIDER_FIRST_LOGIN_ERROR("IDENTITY_PROVIDER_FIRST_LOGIN_ERROR", false),
    IDENTITY_PROVIDER_LINK_ACCOUNT("IDENTITY_PROVIDER_LINK_ACCOUNT", false),
    IDENTITY_PROVIDER_LINK_ACCOUNT_ERROR("IDENTITY_PROVIDER_LINK_ACCOUNT_ERROR", false),
    IDENTITY_PROVIDER_LOGIN("IDENTITY_PROVIDER_LOGIN", false),
    IDENTITY_PROVIDER_LOGIN_ERROR("IDENTITY_PROVIDER_LOGIN_ERROR", false),
    IDENTITY_PROVIDER_POST_LOGIN("IDENTITY_PROVIDER_POST_LOGIN", false),
    IDENTITY_PROVIDER_POST_LOGIN_ERROR("IDENTITY_PROVIDER_POST_LOGIN_ERROR", false),
    IDENTITY_PROVIDER_RESPONSE("IDENTITY_PROVIDER_RESPONSE", false),
    IDENTITY_PROVIDER_RESPONSE_ERROR("IDENTITY_PROVIDER_RESPONSE_ERROR", false),
    IDENTITY_PROVIDER_RETRIEVE_TOKEN("IDENTITY_PROVIDER_RETRIEVE_TOKEN", false),
    IDENTITY_PROVIDER_RETRIEVE_TOKEN_ERROR("IDENTITY_PROVIDER_RETRIEVE_TOKEN_ERROR", false),
    IMPERSONATE("IMPERSONATE", false),
    IMPERSONATE_ERROR("IMPERSONATE_ERROR", false),
    INTROSPECT_TOKEN("INTROSPECT_TOKEN", false),
    INTROSPECT_TOKEN_ERROR("INTROSPECT_TOKEN_ERROR", false),
    INVALID_SIGNATURE("INVALID_SIGNATURE", false),
    INVALID_SIGNATURE_ERROR("INVALID_SIGNATURE_ERROR", false),
    OAUTH2_DEVICE_AUTH("OAUTH2_DEVICE_AUTH", false),
    OAUTH2_DEVICE_AUTH_ERROR("OAUTH2_DEVICE_AUTH_ERROR", false),
    OAUTH2_DEVICE_CODE_TO_TOKEN("OAUTH2_DEVICE_CODE_TO_TOKEN", false),
    OAUTH2_DEVICE_CODE_TO_TOKEN_ERROR("OAUTH2_DEVICE_CODE_TO_TOKEN_ERROR", false),
    OAUTH2_DEVICE_VERIFY_USER_CODE("OAUTH2_DEVICE_VERIFY_USER_CODE", false),
    OAUTH2_DEVICE_VERIFY_USER_CODE_ERROR("OAUTH2_DEVICE_VERIFY_USER_CODE_ERROR", false),
    PERMISSION_TOKEN("PERMISSION_TOKEN", false),
    PERMISSION_TOKEN_ERROR("PERMISSION_TOKEN_ERROR", false),
    PUSHED_AUTHORIZATION_REQUEST("PUSHED_AUTHORIZATION_REQUEST", false),
    PUSHED_AUTHORIZATION_REQUEST_ERROR("PUSHED_AUTHORIZATION_REQUEST_ERROR", false),
    REFRESH_TOKEN("REFRESH_TOKEN", false),
    REFRESH_TOKEN_ERROR("REFRESH_TOKEN_ERROR", false),
    REGISTER_NODE("REGISTER_NODE", false),
    REGISTER_NODE_ERROR("REGISTER_NODE_ERROR", false),
    REMOVE_FEDERATED_IDENTITY("REMOVE_FEDERATED_IDENTITY", false),
    REMOVE_FEDERATED_IDENTITY_ERROR("REMOVE_FEDERATED_IDENTITY_ERROR", false),
    REMOVE_TOTP("REMOVE_TOTP", false),
    REMOVE_TOTP_ERROR("REMOVE_TOTP_ERROR", false),
    RESET_PASSWORD("RESET_PASSWORD", false),
    RESET_PASSWORD_ERROR("RESET_PASSWORD_ERROR", false),
    REVOKE_GRANT("REVOKE_GRANT", false),
    REVOKE_GRANT_ERROR("REVOKE_GRANT_ERROR", false),
    SEND_IDENTITY_PROVIDER_LINK("SEND_IDENTITY_PROVIDER_LINK", false),
    SEND_IDENTITY_PROVIDER_LINK_ERROR("SEND_IDENTITY_PROVIDER_LINK_ERROR", false),
    SEND_RESET_PASSWORD("SEND_RESET_PASSWORD", false),
    SEND_RESET_PASSWORD_ERROR("SEND_RESET_PASSWORD_ERROR", false),
    SEND_VERIFY_EMAIL_ERROR("SEND_VERIFY_EMAIL_ERROR", false),
    TOKEN_EXCHANGE("TOKEN_EXCHANGE", false),
    TOKEN_EXCHANGE_ERROR("TOKEN_EXCHANGE_ERROR", false),
    UNREGISTER_NODE("UNREGISTER_NODE", false),
    UNREGISTER_NODE_ERROR("UNREGISTER_NODE_ERROR", false),
    UPDATE_CONSENT("UPDATE_CONSENT", false),
    UPDATE_CONSENT_ERROR("UPDATE_CONSENT_ERROR", false),
    UPDATE_EMAIL("UPDATE_EMAIL", false),
    UPDATE_EMAIL_ERROR("UPDATE_EMAIL_ERROR", false),
    UPDATE_PASSWORD_ERROR("UPDATE_PASSWORD_ERROR", false),
    UPDATE_PROFILE("UPDATE_PROFILE", false),
    UPDATE_PROFILE_ERROR("UPDATE_PROFILE_ERROR", false),
    UPDATE_TOTP_ERROR("UPDATE_TOTP_ERROR", false),
    USER_INFO_REQUEST("USER_INFO_REQUEST", false),
    USER_INFO_REQUEST_ERROR("USER_INFO_REQUEST_ERROR", false),
    VERIFY_EMAIL_ERROR("VERIFY_EMAIL_ERROR", false),
    VERIFY_PROFILE("VERIFY_PROFILE", false),
    VERIFY_PROFILE_ERROR("VERIFY_PROFILE_ERROR", false);

    private final String value;
    private final boolean shouldProcess;

    KeycloakUserEventType(String value, boolean shouldProcess) {
        this.value = value;
        this.shouldProcess = shouldProcess;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @JsonIgnore
    public boolean shouldProcess() {
        return shouldProcess;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static KeycloakUserEventType fromValue(String value) {
        for (KeycloakUserEventType b : KeycloakUserEventType.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
}
