logging:
  level:
    root: info
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    add-properties: false
    restart:
      enabled: false
    livereload:
      enabled: false
    remote:
      restart:
        enabled: false
server:
  servlet:
    session:
      timeout: 10m