spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
  level:
    root: INFO
    com:
      thanlinardos: TRACE
    org:
      springframework.security: TRACE
      hibernate:
        SQL: TRACE
        orm.jdbc.bind: TRACE
server:
  servlet:
    session:
      timeout: 20m
