server:
  port: 9000
spring:
  application:
    name: authorization-server
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  pattern:
    console: "%cyan(%d{yyyy-MM-dd HH:mm:ss.SSS}) %clr(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  level:
    org.springframework.security: TRACE